markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 12
paginate_path: page/:num

blog:
    name: Robin Li
    description: Bioinformatics and Data Science
    title: Bioinformatics and Data Science
    url: http://PureIce.github.com 
    duoshuo: 冰子-大数据
    tongji: 3Ffb3326a332362ed4b8bc0b37526533f5
author:
    name: Robin Li
    email: r.b.li@foxmail.com 
    weibo: http://weibo.com/u/2310909444
    github: https://github.com/pureice
    logo: http://pureice.github.com/images/me.jpg
